# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu
---
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Ansible ppa, direct internet
  become: yes
  apt_repository: repo='ppa:ansible/ansible' state=present update_cache=yes
  when: not apt_proxy is defined

# https://launchpad.net/~ansible/+archive/ubuntu/ansible
# determining key from ppa page, https://blog.zackad.dev/en/2017/08/17/add-ppa-simple-way.html
- name: Add Ansible Repo Key
  become: yes
  command: apt-key adv --keyserver-options http-proxy={{apt_proxy}} --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6125e2a8c77f2818fb7bd15b93c4a3fd7bb9c367
  when: apt_proxy is defined

- name: Add Ansible ppa, proxy
  become: yes
  apt_repository: repo='ppa:ansible/ansible' state=present update_cache=yes
  environment:
    http_proxy: "{{apt_proxy}}"
    https_proxy: "{{apt_proxy}}"
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: DontWarn
  when: apt_proxy is defined

- name: Install Ansible from ppa
  become: yes
  apt:
    name: ansible
    state: latest
  #apt: name={{item}} state=latest
  #with_items:
  #- ansible
